packages:
  - '.'

# Require all package releases to age for seven days before they are eligible.
minimumReleaseAge: 120

allowBuilds:
  '@matrix-org/matrix-sdk-crypto-nodejs': true
  cpu-features: false
  protobufjs: false
  ssh2: false
