export enum DepotStep {
  UPLOADING_TO_S3 = 'UPLOADING_TO_S3',
  CONTROLE_IN_PROGRESS = 'CONTROLE_IN_PROGRESS',
  CONTROLE_FAILED = 'CONTROLE_FAILED',
  PARSER_SANDRE_IN_PROGRESS = 'PARSER_SANDRE_IN_PROGRESS',
  PARSER_SANDRE_FAILED = 'PARSER_SANDRE_FAILED',
  READY_FOR_SFTP = 'READY_FOR_SFTP',
  SFTP_IN_PROGRESS = 'SFTP_IN_PROGRESS',
  SFTP_FAILED = 'SFTP_FAILED',
  SFTP_COMPLETED = 'SFTP_COMPLETED',
}

export enum DepotStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  FAILED = 'FAILED',
  SUCCESS = 'SUCCESS',
}
