export enum DepotStep {
  PENDING = 'PENDING',
  UPLOADING_TO_S3 = 'UPLOADING_TO_S3',
  CONTROLE_IN_PROGRESS = 'CONTROLE_IN_PROGRESS',
  CONTROLE_COMPLETED = 'CONTROLE_COMPLETED',
  CONTROLE_FAILED = 'CONTROLE_FAILED',
  CONTROLE_SANDRE_IN_PROGRESS = 'CONTROLE_SANDRE_IN_PROGRESS',
  CONTROLE_SANDRE_COMPLETED = 'CONTROLE_SANDRE_COMPLETED',
  CONTROLE_SANDRE_FAILED = 'CONTROLE_SANDRE_FAILED',
  PARSER_SANDRE_IN_PROGRESS = 'PARSER_SANDRE_IN_PROGRESS',
  PARSER_SANDRE_FAILED = 'PARSER_SANDRE_FAILED',
  READY_FOR_SFTP = 'READY_FOR_SFTP',
  SFTP_IN_PROGRESS = 'SFTP_IN_PROGRESS',
  SFTP_FAILED = 'SFTP_FAILED',
  SFTP_COMPLETED = 'SFTP_COMPLETED',
  MASA_CALLED_ENPOINT = 'MASA_CALLED_ENPOINT',
  SEND_TO_AGENCE_DE_L_EAU = 'SEND_TO_AGENCE_DE_L_EAU',
  SEND_EMAIL_TO_DEPOSANT = 'SEND_EMAIL_TO_DEPOSANT',
}

export enum DepotStatus {
  EN_COURS_DE_TRAITEMENT = 'EN_COURS_DE_TRAITEMENT',
  INTEGRE = 'INTEGRE',
  INTEGRE_PARTIELLEMENT = 'INTEGRE_PARTIELLEMENT',
  REJETE = 'REJETE',
}

export enum EtapeMetier {
  CONTROLE_REFERENTIEL = 'CONTROLE_REFERENTIEL',
  CONTROLE_METIER = 'CONTROLE_METIER',
  SCENARIO_SANDRE = 'SCENARIO_SANDRE',
  FINALISATION_IMPORT = 'FINALISATION_IMPORT',
}

export enum ControleStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum ControleSandreStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}
