export enum DepotError {
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  ENQUEUE_FAILED = 'ENQUEUE_FAILED',
  DROITS_INSUFFISANTS = 'DROITS_INSUFFISANTS',
  FLUX_QUALIFIE_INTERDIT = 'FLUX_QUALIFIE_INTERDIT',
  SANDRE_UPLOAD_FAILED = 'SANDRE_UPLOAD_FAILED',
  SANDRE_POLL_TIMEOUT = 'SANDRE_POLL_TIMEOUT',
  SANDRE_POLL_FAILED = 'SANDRE_POLL_FAILED',
  CONTROLE_METIER_FAILED = 'CONTROLE_METIER_FAILED',
}

export class DepotRightsException extends Error {
  constructor(public readonly code: DepotError) {
    super(code);
    this.name = 'DepotRightsException';
  }
}
